title: Narges Tavassoli
logo: assets/img/me.png
description: narges [dot] tavassoli-kejani [at] univ-lille [dot] fr  
# Oficce: S03.06, Bâtiment ESPRIT, CRIStAL, Villeneuve d'Ascq, France   
# Email: narges [dot] tavassoli-kejani [at] univ-lille [dot] fr   
# Email: tavassoli [dot] narges [at] gmail [dot] com   
Profiles: [LinkedIn](https://www.linkedin.com/in/narges-tavassoli)  
# show_downloads: true
theme: jekyll-theme-minimal
